<?php
/**
 * Keyword engine – generates, expands and clusters keywords using AI.
 *
 * Responsibilities:
 *  1. Generate a list of related keywords from a seed phrase.
 *  2. Expand a topic into long-tail variants.
 *  3. Build a {@see KeywordCluster} (pillar + supporting keywords) ready for
 *     the content pipeline.
 *
 * @package PearBlogEngine\Keywords
 */

declare(strict_types=1);

namespace PearBlogEngine\Keywords;

use PearBlogEngine\AI\AIClient;
use PearBlogEngine\Tenant\SiteProfile;

/**
 * AI-powered keyword research and clustering.
 */
class KeywordEngine {

	/** @var SiteProfile */
	private SiteProfile $profile;

	/** @var AIClient */
	private AIClient $ai;

	public function __construct( SiteProfile $profile, ?AIClient $ai = null ) {
		$this->profile = $profile;
		$this->ai      = $ai ?? new AIClient();
	}

	// -----------------------------------------------------------------------
	// Public API
	// -----------------------------------------------------------------------

	/**
	 * Generate keyword ideas from a seed phrase.
	 *
	 * Uses the AI to produce a list of related keywords and long-tail variants
	 * that match the tenant's industry and language.
	 *
	 * @param string $seed  The seed keyword / topic.
	 * @param int    $count Desired number of keyword ideas (approximate).
	 * @return string[]     Array of keyword strings.
	 */
	public function generate_from_seed( string $seed, int $count = 10 ): array {
		$seed    = trim( $seed );
		$profile = $this->profile;
		$count   = max( 1, min( $count, 50 ) );

		$prompt = "You are an SEO keyword research specialist.\n";
		$prompt .= "Industry: {$profile->industry}. Language: {$profile->language}.\n";
		$prompt .= "Generate exactly {$count} unique, high-value SEO keywords related to: \"{$seed}\".\n";
		$prompt .= "Include a mix of short-tail and long-tail keywords.\n";
		$prompt .= "Output ONLY a plain numbered list, one keyword per line, no explanations.\n";
		$prompt .= "Example:\n1. keyword one\n2. another keyword\n";

		$raw = $this->ai->generate( $prompt, 512 );

		return $this->parse_numbered_list( $raw );
	}

	/**
	 * Expand a topic into a set of long-tail keyword variants.
	 *
	 * @param string $topic  The base topic.
	 * @param int    $count  Number of long-tail variants to generate.
	 * @return string[]
	 */
	public function expand_topics( string $topic, int $count = 8 ): array {
		$topic   = trim( $topic );
		$profile = $this->profile;
		$count   = max( 1, min( $count, 30 ) );

		$prompt = "You are an SEO content strategist.\n";
		$prompt .= "Industry: {$profile->industry}. Language: {$profile->language}.\n";
		$prompt .= "Create exactly {$count} long-tail keyword variations for: \"{$topic}\".\n";
		$prompt .= "Each variation should be a specific, search-intent-driven phrase (4–8 words).\n";
		$prompt .= "Output ONLY a plain numbered list, one keyword per line, no explanations.\n";

		$raw = $this->ai->generate( $prompt, 512 );

		return $this->parse_numbered_list( $raw );
	}

	/**
	 * Build a full keyword cluster (pillar + supporting keywords) from a seed.
	 *
	 * The pillar keyword is the seed itself (cleaned up); supporting keywords
	 * are long-tail expansions generated by the AI.
	 *
	 * @param string $pillar_seed  The broad topic / pillar keyword.
	 * @param int    $supporting   Number of supporting keywords to generate.
	 * @return KeywordCluster
	 */
	public function build_cluster( string $pillar_seed, int $supporting = 6 ): KeywordCluster {
		$pillar_seed = trim( $pillar_seed );

		$supporting_keywords = $this->expand_topics( $pillar_seed, $supporting );

		$cluster = new KeywordCluster( $pillar_seed, $supporting_keywords );

		/**
		 * Filter: pearblog_keyword_cluster
		 *
		 * Allows external code to modify a cluster before it enters the pipeline.
		 *
		 * @param KeywordCluster $cluster      The assembled cluster.
		 * @param string         $pillar_seed  Original seed.
		 * @param SiteProfile    $profile      Active site profile.
		 */
		return apply_filters( 'pearblog_keyword_cluster', $cluster, $pillar_seed, $this->profile );
	}

	// -----------------------------------------------------------------------
	// Private helpers
	// -----------------------------------------------------------------------

	/**
	 * Parse a numbered list (e.g. "1. foo\n2. bar") into an array of strings.
	 *
	 * @param string $raw Raw AI output.
	 * @return string[]
	 */
	private function parse_numbered_list( string $raw ): array {
		$lines    = preg_split( '/\r?\n/', trim( $raw ) );
		$keywords = [];

		foreach ( $lines as $line ) {
			// Strip leading numbering (e.g. "1. ", "12. ") and bullet characters.
			$cleaned = preg_replace( '/^\s*[\d]+[.)]\s*/', '', trim( $line ) );
			$cleaned = ltrim( $cleaned, '-*• ' );
			$cleaned = trim( $cleaned );

			if ( '' !== $cleaned ) {
				$keywords[] = $cleaned;
			}
		}

		return $keywords;
	}
}
