<?php
/**
 * Post Meta Manager
 *
 * Manages additional meta fields for posts: reading_time, difficulty_level, ai_generated.
 * Automatically calculates reading time and integrates with the content pipeline.
 *
 * @package PearBlogEngine\Content
 */

declare(strict_types=1);

namespace PearBlogEngine\Content;

/**
 * Manages extended post meta fields.
 */
class PostMetaManager {

	/** Average words per minute for reading time calculation. */
	private const WORDS_PER_MINUTE = 200;

	/**
	 * Register hooks.
	 */
	public function register(): void {
		add_action( 'add_meta_boxes', [ $this, 'add_meta_boxes' ] );
		add_action( 'save_post', [ $this, 'save_meta' ], 10, 2 );
		add_action( 'save_post', [ $this, 'auto_calculate_reading_time' ], 20, 2 );
	}

	/**
	 * Add meta boxes for post fields.
	 */
	public function add_meta_boxes(): void {
		add_meta_box(
			'pb_post_meta',
			__( 'Article Metadata', 'pearblog-engine' ),
			[ $this, 'render_meta_box' ],
			'post',
			'side',
			'default'
		);
	}

	/**
	 * Render post meta box.
	 *
	 * @param \WP_Post $post Current post object.
	 */
	public function render_meta_box( \WP_Post $post ): void {
		wp_nonce_field( 'pb_post_meta', 'pb_post_meta_nonce' );

		$reading_time     = get_post_meta( $post->ID, '_pb_reading_time', true );
		$difficulty_level = get_post_meta( $post->ID, '_pb_difficulty_level', true );
		$ai_generated     = get_post_meta( $post->ID, '_pb_ai_generated', true );

		?>
		<table class="form-table">
			<tr>
				<td>
					<label for="pb_reading_time">
						<strong><?php esc_html_e( 'Reading Time (minutes)', 'pearblog-engine' ); ?></strong>
					</label>
					<input type="number" id="pb_reading_time" name="pb_reading_time" value="<?php echo esc_attr( $reading_time ); ?>" min="1" max="60" class="small-text" />
					<p class="description"><?php esc_html_e( 'Auto-calculated on save. Override if needed.', 'pearblog-engine' ); ?></p>
				</td>
			</tr>
			<tr>
				<td>
					<label for="pb_difficulty_level">
						<strong><?php esc_html_e( 'Difficulty Level', 'pearblog-engine' ); ?></strong>
					</label>
					<select id="pb_difficulty_level" name="pb_difficulty_level" class="widefat">
						<option value=""><?php esc_html_e( 'Not set', 'pearblog-engine' ); ?></option>
						<option value="beginner" <?php selected( $difficulty_level, 'beginner' ); ?>><?php esc_html_e( 'Beginner', 'pearblog-engine' ); ?></option>
						<option value="intermediate" <?php selected( $difficulty_level, 'intermediate' ); ?>><?php esc_html_e( 'Intermediate', 'pearblog-engine' ); ?></option>
						<option value="advanced" <?php selected( $difficulty_level, 'advanced' ); ?>><?php esc_html_e( 'Advanced', 'pearblog-engine' ); ?></option>
						<option value="expert" <?php selected( $difficulty_level, 'expert' ); ?>><?php esc_html_e( 'Expert', 'pearblog-engine' ); ?></option>
					</select>
				</td>
			</tr>
			<tr>
				<td>
					<label>
						<input type="checkbox" name="pb_ai_generated" value="1" <?php checked( $ai_generated, '1' ); ?> />
						<strong><?php esc_html_e( 'AI Generated', 'pearblog-engine' ); ?></strong>
					</label>
					<p class="description"><?php esc_html_e( 'Mark if this article was generated by AI.', 'pearblog-engine' ); ?></p>
				</td>
			</tr>
		</table>
		<?php
	}

	/**
	 * Save post meta data.
	 *
	 * @param int      $post_id Post ID.
	 * @param \WP_Post $post    Post object.
	 */
	public function save_meta( int $post_id, \WP_Post $post ): void {
		// Verify nonce.
		if ( ! isset( $_POST['pb_post_meta_nonce'] ) || ! wp_verify_nonce( $_POST['pb_post_meta_nonce'], 'pb_post_meta' ) ) {
			return;
		}

		// Check autosave.
		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
			return;
		}

		// Check permissions.
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}

		// Check post type.
		if ( 'post' !== $post->post_type ) {
			return;
		}

		// Save reading time (if manually set).
		if ( isset( $_POST['pb_reading_time'] ) && '' !== $_POST['pb_reading_time'] ) {
			update_post_meta( $post_id, '_pb_reading_time', absint( $_POST['pb_reading_time'] ) );
		}

		// Save difficulty level.
		if ( isset( $_POST['pb_difficulty_level'] ) ) {
			$difficulty = sanitize_text_field( $_POST['pb_difficulty_level'] );
			if ( in_array( $difficulty, [ '', 'beginner', 'intermediate', 'advanced', 'expert' ], true ) ) {
				update_post_meta( $post_id, '_pb_difficulty_level', $difficulty );
			}
		}

		// Save AI generated flag.
		$ai_generated = isset( $_POST['pb_ai_generated'] ) ? '1' : '0';
		update_post_meta( $post_id, '_pb_ai_generated', $ai_generated );
	}

	/**
	 * Auto-calculate reading time based on word count.
	 *
	 * @param int      $post_id Post ID.
	 * @param \WP_Post $post    Post object.
	 */
	public function auto_calculate_reading_time( int $post_id, \WP_Post $post ): void {
		// Only for posts.
		if ( 'post' !== $post->post_type ) {
			return;
		}

		// Only if reading time wasn't manually set in this save.
		if ( isset( $_POST['pb_reading_time'] ) && '' !== $_POST['pb_reading_time'] ) {
			return;
		}

		$reading_time = self::calculate_reading_time( $post->post_content );

		update_post_meta( $post_id, '_pb_reading_time', $reading_time );
	}

	/**
	 * Calculate reading time for content.
	 *
	 * @param string $content Post content.
	 * @return int Reading time in minutes.
	 */
	public static function calculate_reading_time( string $content ): int {
		// Strip HTML tags and get word count.
		$text       = wp_strip_all_tags( $content );
		$word_count = str_word_count( $text );

		// Calculate reading time (minimum 1 minute).
		$reading_time = max( 1, (int) ceil( $word_count / self::WORDS_PER_MINUTE ) );

		return $reading_time;
	}

	/**
	 * Set post meta fields programmatically (used by AI pipeline).
	 *
	 * @param int   $post_id          Post ID.
	 * @param array $meta             Meta data array.
	 */
	public static function set_post_meta( int $post_id, array $meta ): void {
		if ( isset( $meta['reading_time'] ) ) {
			update_post_meta( $post_id, '_pb_reading_time', absint( $meta['reading_time'] ) );
		}

		if ( isset( $meta['difficulty_level'] ) ) {
			$difficulty = sanitize_text_field( $meta['difficulty_level'] );
			if ( in_array( $difficulty, [ 'beginner', 'intermediate', 'advanced', 'expert' ], true ) ) {
				update_post_meta( $post_id, '_pb_difficulty_level', $difficulty );
			}
		}

		if ( isset( $meta['ai_generated'] ) ) {
			update_post_meta( $post_id, '_pb_ai_generated', $meta['ai_generated'] ? '1' : '0' );
		}
	}

	/**
	 * Get post meta fields as structured array.
	 *
	 * @param int $post_id Post ID.
	 * @return array Post meta data.
	 */
	public static function get_post_meta( int $post_id ): array {
		return [
			'reading_time'     => get_post_meta( $post_id, '_pb_reading_time', true ),
			'difficulty_level' => get_post_meta( $post_id, '_pb_difficulty_level', true ),
			'ai_generated'     => (bool) get_post_meta( $post_id, '_pb_ai_generated', true ),
		];
	}

	/**
	 * Display reading time badge in article.
	 *
	 * @param int $post_id Post ID.
	 * @return string HTML output.
	 */
	public static function display_reading_time( int $post_id ): string {
		$reading_time = get_post_meta( $post_id, '_pb_reading_time', true );

		if ( ! $reading_time ) {
			return '';
		}

		$text = sprintf(
			/* translators: %d: Reading time in minutes */
			_n( '%d minute read', '%d minutes read', $reading_time, 'pearblog-engine' ),
			$reading_time
		);

		return sprintf( '<span class="pb-reading-time">⏱️ %s</span>', esc_html( $text ) );
	}

	/**
	 * Display difficulty level badge in article.
	 *
	 * @param int $post_id Post ID.
	 * @return string HTML output.
	 */
	public static function display_difficulty_level( int $post_id ): string {
		$difficulty = get_post_meta( $post_id, '_pb_difficulty_level', true );

		if ( ! $difficulty ) {
			return '';
		}

		$labels = [
			'beginner'     => __( 'Beginner', 'pearblog-engine' ),
			'intermediate' => __( 'Intermediate', 'pearblog-engine' ),
			'advanced'     => __( 'Advanced', 'pearblog-engine' ),
			'expert'       => __( 'Expert', 'pearblog-engine' ),
		];

		$label = $labels[ $difficulty ] ?? ucfirst( $difficulty );

		return sprintf( '<span class="pb-difficulty-level pb-difficulty-%s">📊 %s</span>', esc_attr( $difficulty ), esc_html( $label ) );
	}
}
