<?php
/**
 * PT24.PRO — blog archive routing.
 *
 * The shared theme's index.php is the poradnik.pro V3 conversion layout, which
 * would otherwise render on PT24's /blog/ posts index. Route the posts index to
 * the dedicated PT24 blog template instead. Loaded only on the PT24 install
 * (host-guarded require), so poradnik.pro / mucharski.pl are untouched.
 *
 * @package PearBlog
 * @subpackage PT24
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Self-heal: ensure page_for_posts points to the /blog/ page if it's missing.
 * Runs at init priority 1 so WP can detect is_home() correctly.
 */
add_action( 'init', static function() {
	$posts_page = (int) get_option( 'page_for_posts', 0 );
	if ( $posts_page <= 0 ) {
		$blog = get_page_by_path( 'blog' );
		if ( $blog instanceof WP_Post ) {
			update_option( 'page_for_posts', $blog->ID );
			update_option( 'show_on_front', 'page' );
		}
	}
}, 1 );

/**
 * Use the PT24 blog archive template for the posts index (/blog/).
 */
function pt24_blog_template_include( $template ) {
	// Primary check: queried object matches page_for_posts option
	$posts_page = (int) get_option( 'page_for_posts' );
	if (
		$posts_page > 0
		&& is_home()
		&& ! is_singular()
		&& (int) get_queried_object_id() === $posts_page
	) {
		$custom = locate_template( 'pt24-blog-archive.php' );
		if ( $custom ) {
			return $custom;
		}
	}

	// Fallback: match /blog/ path directly in case page_for_posts is stale
	$uri  = isset( $_SERVER['REQUEST_URI'] ) ? (string) wp_unslash( $_SERVER['REQUEST_URI'] ) : '';
	$path = (string) wp_parse_url( $uri, PHP_URL_PATH );
	$home_path = untrailingslashit( (string) wp_parse_url( home_url( '/' ), PHP_URL_PATH ) );
	if ( '' !== $home_path && '/' !== $home_path && 0 === strpos( $path, $home_path ) ) {
		$path = substr( $path, strlen( $home_path ) );
	}
	if ( preg_match( '#^/?blog/?$#', $path ) ) {
		// Auto-fix page_for_posts while we're here
		if ( 0 === $posts_page ) {
			$blog = get_page_by_path( 'blog' );
			if ( $blog instanceof WP_Post ) {
				update_option( 'page_for_posts', $blog->ID );
				update_option( 'show_on_front', 'page' );
			}
		}
		$custom = locate_template( 'pt24-blog-archive.php' );
		if ( $custom ) {
			// Force WP into blog-index mode for correct have_posts() etc.
			global $wp_query;
			$wp_query->is_home = true;
			$wp_query->is_page = false;
			if ( 0 === $wp_query->posts_per_page || $wp_query->found_posts === 0 ) {
				$blog_q = new WP_Query( [
					'post_type'           => 'post',
					'post_status'         => 'publish',
					'posts_per_page'      => (int) get_option( 'posts_per_page', 10 ),
					'paged'               => max( 1, (int) get_query_var( 'paged' ) ),
					'ignore_sticky_posts' => true,
				] );
				$wp_query = $blog_q;
				rewind_posts();
			}
			return $custom;
		}
	}

	return $template;
}
add_filter( 'template_include', 'pt24_blog_template_include', 99 );

/**
 * Route single blog posts generated by PT24_Blog_Engine to single-pt24_blog.php.
 * Posts are identified by the _pt24_blog_ai meta flag.
 */
add_filter( 'template_include', static function( $template ) {
	if ( ! is_singular( 'post' ) ) {
		return $template;
	}
	if ( '1' !== (string) get_post_meta( get_the_ID(), '_pt24_blog_ai', true ) ) {
		return $template;
	}
	$custom = locate_template( 'single-pt24_blog.php' );
	return $custom ?: $template;
}, 100 );
