<?php
/**
 * PT24 REST API Endpoints
 *
 * REST API for PT24 platform
 *
 * @package PearBlog
 * @version 1.0.0
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Register REST API routes
 */
function pt24_register_rest_routes() {
    // Namespace
    $namespace = 'pt24/v1';

    // Get businesses endpoint
    register_rest_route($namespace, '/businesses', [
        'methods' => 'GET',
        'callback' => 'pt24_api_get_businesses',
        'permission_callback' => '__return_true',
        'args' => [
            'service' => [
                'required' => false,
                'type' => 'string',
            ],
            'city' => [
                'required' => false,
                'type' => 'string',
            ],
            'per_page' => [
                'default' => 10,
                'type' => 'integer',
            ],
            'page' => [
                'default' => 1,
                'type' => 'integer',
            ],
            'min_rating' => [
                'required' => false,
                'type' => 'number',
            ],
            'mobile_service' => [
                'required' => false,
                'type' => 'boolean',
            ],
            'available_today' => [
                'required' => false,
                'type' => 'boolean',
            ],
            'sort_by' => [
                'required' => false,
                'type' => 'string',
                'default' => 'rating',
            ],
            'sort_order' => [
                'required' => false,
                'type' => 'string',
                'default' => 'desc',
            ],
        ],
    ]);

    // Get single business endpoint
    register_rest_route($namespace, '/businesses/(?P<id>\d+)', [
        'methods' => 'GET',
        'callback' => 'pt24_api_get_business',
        'permission_callback' => '__return_true',
    ]);

    // Get leads endpoint (admin only)
    register_rest_route($namespace, '/leads', [
        'methods' => 'GET',
        'callback' => 'pt24_api_get_leads',
        'permission_callback' => function() {
            return current_user_can('manage_options');
        },
        'args' => [
            'status' => [
                'required' => false,
                'type' => 'string',
            ],
            'per_page' => [
                'default' => 20,
                'type' => 'integer',
            ],
            'page' => [
                'default' => 1,
                'type' => 'integer',
            ],
        ],
    ]);

    // Get business stats endpoint (business owner or admin)
    register_rest_route($namespace, '/stats/(?P<business_id>\d+)', [
        'methods' => 'GET',
        'callback' => 'pt24_api_get_business_stats',
        'permission_callback' => 'pt24_api_can_view_stats',
    ]);

    // Submit lead endpoint (public)
    register_rest_route($namespace, '/leads/submit', [
        'methods' => 'POST',
        'callback' => 'pt24_api_submit_lead',
        'permission_callback' => '__return_true',
    ]);
}
add_action('rest_api_init', 'pt24_register_rest_routes');

/**
 * Clear cached PT24 business listing responses.
 *
 * Uses a prefix delete for transient rows generated by pt24_api_get_businesses().
 */
function pt24_api_invalidate_business_list_cache() {
    global $wpdb;

    if (!($wpdb instanceof wpdb)) {
        return;
    }

    $options_table = $wpdb->options;

    $wpdb->query(
        $wpdb->prepare(
            "DELETE FROM {$options_table} WHERE option_name LIKE %s OR option_name LIKE %s",
            $wpdb->esc_like('_transient_pt24_api_biz_') . '%',
            $wpdb->esc_like('_transient_timeout_pt24_api_biz_') . '%'
        )
    );
}

/**
 * Invalidate PT24 listing cache when business-related posts change.
 */
function pt24_api_invalidate_cache_on_post_change($post_id, $post = null, $update = null) {
    unset($update);

    if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) {
        return;
    }

    if (!is_numeric($post_id) || ((int) $post_id) <= 0) {
        return;
    }

    if (null === $post) {
        $post = get_post((int) $post_id);
    }

    if (!($post instanceof WP_Post)) {
        return;
    }

    if (!in_array($post->post_type, ['pt24_business', 'pt24_firm'], true)) {
        return;
    }

    pt24_api_invalidate_business_list_cache();
}
add_action('save_post_pt24_business', 'pt24_api_invalidate_cache_on_post_change', 10, 3);
add_action('save_post_pt24_firm', 'pt24_api_invalidate_cache_on_post_change', 10, 3);
add_action('delete_post', 'pt24_api_invalidate_cache_on_post_change', 10, 1);

/**
 * Get businesses
 */
function pt24_api_get_businesses($request) {
    $service = $request->get_param('service');
    $city = $request->get_param('city');
    $per_page = max(1, min(50, absint($request->get_param('per_page'))));
    $page = max(1, absint($request->get_param('page')));
    $min_rating = (float) $request->get_param('min_rating');
    $mobile_service_raw = $request->get_param('mobile_service');
    $available_today_raw = $request->get_param('available_today');
    $sort_by = (string) $request->get_param('sort_by');
    $sort_order = strtoupper((string) $request->get_param('sort_order'));

    $normalize_nullable_bool = static function ($value) {
        if (null === $value || '' === $value) {
            return null;
        }

        if (is_bool($value)) {
            return $value;
        }

        if (is_numeric($value)) {
            return ((int) $value) > 0;
        }

        $normalized = strtolower(trim((string) $value));
        if (in_array($normalized, ['1', 'true', 'yes', 'on'], true)) {
            return true;
        }
        if (in_array($normalized, ['0', 'false', 'no', 'off'], true)) {
            return false;
        }

        return null;
    };

    $mobile_service = $normalize_nullable_bool($mobile_service_raw);
    $available_today = $normalize_nullable_bool($available_today_raw);

    $args = [
        'post_type' => 'pt24_business',
        'post_status' => 'publish',
        'posts_per_page' => $per_page,
        'paged' => $page,
        'no_found_rows' => false,
        'update_post_meta_cache' => true,
        'update_post_term_cache' => true,
    ];

    // Add tax query if service or city specified
    if ($service || $city) {
        $args['tax_query'] = ['relation' => 'AND'];

        if ($service) {
            $args['tax_query'][] = [
                'taxonomy' => 'pt24_service_cat',
                'field' => 'slug',
                'terms' => $service,
            ];
        }

        if ($city) {
            $args['tax_query'][] = [
                'taxonomy' => 'pt24_city',
                'field' => 'slug',
                'terms' => $city,
            ];
        }
    }

    $args['meta_query'] = ['relation' => 'AND'];

    if ($min_rating > 0) {
        $args['meta_query'][] = [
            'key' => 'pt24_rating',
            'value' => $min_rating,
            'type' => 'NUMERIC',
            'compare' => '>=',
        ];
    }

    if (null !== $mobile_service) {
        $args['meta_query'][] = [
            'key' => 'pt24_mobile_service',
            'value' => $mobile_service ? '1' : '0',
            'compare' => '=',
        ];
    }

    if (null !== $available_today) {
        $args['meta_query'][] = [
            'key' => 'pt24_available_today',
            'value' => $available_today ? '1' : '0',
            'compare' => '=',
        ];
    }

    if (1 === count($args['meta_query'])) {
        unset($args['meta_query']);
    }

    if ('ASC' !== $sort_order) {
        $sort_order = 'DESC';
    }

    switch ($sort_by) {
        case 'name':
            $args['orderby'] = 'title';
            $args['order'] = $sort_order;
            break;
        case 'reviews':
            $args['meta_key'] = 'pt24_reviews_count';
            $args['orderby'] = 'meta_value_num';
            $args['order'] = $sort_order;
            break;
        case 'newest':
            $args['orderby'] = 'date';
            $args['order'] = $sort_order;
            break;
        case 'rating':
        default:
            $args['meta_key'] = 'pt24_rating';
            $args['orderby'] = 'meta_value_num';
            $args['order'] = $sort_order;
            break;
    }

    $cache_key = 'pt24_api_biz_' . md5(wp_json_encode($args));
    $cached_response = get_transient($cache_key);
    if (is_array($cached_response)) {
        return new WP_REST_Response($cached_response, 200);
    }

    $query = new WP_Query($args);
    $businesses = [];

    foreach ($query->posts as $post) {
        $businesses[] = [
            'id' => $post->ID,
            'name' => $post->post_title,
            'url' => get_permalink($post->ID),
            'phone' => get_post_meta($post->ID, 'pt24_phone', true),
            'email' => get_post_meta($post->ID, 'pt24_email', true),
            'service_area' => get_post_meta($post->ID, 'pt24_service_area', true),
            'rating' => floatval(get_post_meta($post->ID, 'pt24_rating', true) ?: 5),
            'reviews_count' => intval(get_post_meta($post->ID, 'pt24_reviews_count', true) ?: 0),
            'mobile_service' => (bool) get_post_meta($post->ID, 'pt24_mobile_service', true),
            'available_today' => (bool) get_post_meta($post->ID, 'pt24_available_today', true),
            'lat' => (float) get_post_meta($post->ID, 'pt24_lat', true),
            'lng' => (float) get_post_meta($post->ID, 'pt24_lng', true),
            'plan' => get_post_meta($post->ID, 'pt24_plan', true) ?: 'free',
        ];
    }

    $response = [
        'businesses' => $businesses,
        'total' => (int) $query->found_posts,
        'pages' => (int) $query->max_num_pages,
        'current_page' => $page,
        'per_page' => $per_page,
        'filters' => [
            'service' => $service,
            'city' => $city,
            'min_rating' => $min_rating,
            'mobile_service' => $mobile_service,
            'available_today' => $available_today,
            'sort_by' => $sort_by,
            'sort_order' => strtolower($sort_order),
        ],
    ];

    set_transient($cache_key, $response, 5 * MINUTE_IN_SECONDS);

    return new WP_REST_Response($response, 200);
}

/**
 * Get single business
 */
function pt24_api_get_business($request) {
    $business_id = $request->get_param('id');
    $post = get_post($business_id);

    if (!$post || $post->post_type !== 'pt24_business' || $post->post_status !== 'publish') {
        return new WP_Error('not_found', 'Business not found', ['status' => 404]);
    }

    $categories = get_the_terms($business_id, 'pt24_service_cat');
    $cities = get_the_terms($business_id, 'pt24_city');

    $business = [
        'id' => $post->ID,
        'name' => $post->post_title,
        'content' => apply_filters('the_content', $post->post_content),
        'url' => get_permalink($post->ID),
        'phone' => get_post_meta($business_id, 'pt24_phone', true),
        'email' => get_post_meta($business_id, 'pt24_email', true),
        'website' => get_post_meta($business_id, 'pt24_website', true),
        'service_area' => get_post_meta($business_id, 'pt24_service_area', true),
        'specialization' => get_post_meta($business_id, 'pt24_specialization', true),
        'years_experience' => intval(get_post_meta($business_id, 'pt24_years_experience', true) ?: 0),
        'mobile_service' => (bool) get_post_meta($business_id, 'pt24_mobile_service', true),
        'rating' => floatval(get_post_meta($business_id, 'pt24_rating', true) ?: 5),
        'reviews_count' => intval(get_post_meta($business_id, 'pt24_reviews_count', true) ?: 0),
        'plan' => get_post_meta($business_id, 'pt24_plan', true) ?: 'free',
        'services' => $categories ? array_map(function($term) {
            return $term->name;
        }, $categories) : [],
        'cities' => $cities ? array_map(function($term) {
            return $term->name;
        }, $cities) : [],
    ];

    return new WP_REST_Response($business, 200);
}

/**
 * Get leads (admin only)
 */
function pt24_api_get_leads($request) {
    global $wpdb;
    $table_name = $wpdb->prefix . 'pt24_leads';

    $status = $request->get_param('status');
    $per_page = max(1, min(100, absint($request->get_param('per_page'))));
    $page = max(1, absint($request->get_param('page')));
    $offset = ($page - 1) * $per_page;

    $where_sql = '';
    $where_values = [];

    if (!empty($status)) {
        $where_sql = 'WHERE status = %s';
        $where_values[] = sanitize_key($status);
    }

    $leads_query = "SELECT * FROM $table_name $where_sql ORDER BY created_at DESC LIMIT %d OFFSET %d";
    $leads_values = array_merge($where_values, [$per_page, $offset]);
    $prepared_leads_query = $wpdb->prepare($leads_query, $leads_values);
    $leads = $wpdb->get_results($prepared_leads_query);

    $count_query = "SELECT COUNT(*) FROM $table_name $where_sql";
    if (!empty($where_values)) {
        $prepared_count_query = $wpdb->prepare($count_query, $where_values);
        $total = $wpdb->get_var($prepared_count_query);
    } else {
        $total = $wpdb->get_var($count_query);
    }

    return new WP_REST_Response([
        'leads' => $leads,
        'total' => intval($total),
        'pages' => ceil($total / $per_page),
        'current_page' => $page,
    ], 200);
}

/**
 * Get business stats
 */
function pt24_api_get_business_stats($request) {
    $business_id = $request->get_param('business_id');

    global $wpdb;
    $table_name = $wpdb->prefix . 'pt24_business_stats';

    // Get last 30 days stats
    $thirty_days_ago = date('Y-m-d', strtotime('-30 days'));
    $stats = $wpdb->get_results($wpdb->prepare(
        "SELECT * FROM $table_name WHERE business_id = %d AND date >= %s ORDER BY date DESC",
        $business_id,
        $thirty_days_ago
    ));

    // Calculate totals
    $totals = [
        'views' => 0,
        'phone_clicks' => 0,
        'email_clicks' => 0,
    ];

    foreach ($stats as $day_stat) {
        $totals['views'] += $day_stat->views;
        $totals['phone_clicks'] += $day_stat->phone_clicks;
        $totals['email_clicks'] += $day_stat->email_clicks;
    }

    return new WP_REST_Response([
        'daily_stats' => $stats,
        'totals_30_days' => $totals,
    ], 200);
}

/**
 * Check if user can view stats
 */
function pt24_api_can_view_stats($request) {
    // Admin can view all stats
    if (current_user_can('manage_options')) {
        return true;
    }

    // Business owner can view their own stats
    $business_id = $request->get_param('business_id');
    $post = get_post($business_id);

    if ($post && get_current_user_id() === $post->post_author) {
        return true;
    }

    return false;
}

/**
 * Submit lead via API
 */
function pt24_api_submit_lead($request) {
    $params = $request->get_json_params();
    if (!is_array($params) || empty($params)) {
        $params = $request->get_params();
    }

    $lead_rate_limit_window = defined('MINUTE_IN_SECONDS') ? MINUTE_IN_SECONDS : 60;
    $client_ip = isset($_SERVER['REMOTE_ADDR']) ? sanitize_text_field((string) wp_unslash($_SERVER['REMOTE_ADDR'])) : 'unknown';
    $rate_limit_key = 'pt24_api_lead_rl_' . md5($client_ip);

    if (false !== get_transient($rate_limit_key)) {
        return new WP_Error('rate_limited', 'Please wait before sending another lead request.', ['status' => 429]);
    }

    // Validate required fields
    $required = ['name', 'email', 'phone', 'city', 'service'];
    foreach ($required as $field) {
        if (empty($params[$field])) {
            return new WP_Error('missing_field', "Field '$field' is required", ['status' => 400]);
        }
    }

    // Sanitize
    $name = sanitize_text_field($params['name']);
    $email = sanitize_email($params['email']);
    $phone = sanitize_text_field($params['phone']);
    $phone = preg_replace('/[^0-9+\s()-]/', '', $phone);
    $city = sanitize_text_field($params['city']);
    $service = sanitize_text_field($params['service']);
    $message = sanitize_textarea_field($params['message'] ?? '');

    // Validate email
    if (!is_email($email)) {
        return new WP_Error('invalid_email', 'Invalid email address', ['status' => 400]);
    }

    if (strlen((string) $phone) < 6) {
        return new WP_Error('invalid_phone', 'Invalid phone number', ['status' => 400]);
    }

    // Store in database
    global $wpdb;
    $table_name = $wpdb->prefix . 'pt24_leads';

    $result = $wpdb->insert(
        $table_name,
        [
            'name' => $name,
            'email' => $email,
            'phone' => $phone,
            'city' => $city,
            'service' => $service,
            'message' => $message,
            'source' => 'api',
            'status' => 'new',
            'created_at' => current_time('mysql'),
        ],
        ['%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
    );

    if ($result === false) {
        return new WP_Error('insert_failed', 'Failed to save lead', ['status' => 500]);
    }

    // New lead impacts dashboards and listing freshness; purge cached listings.
    pt24_api_invalidate_business_list_cache();

    set_transient($rate_limit_key, 1, $lead_rate_limit_window);

    $lead_id = $wpdb->insert_id;

    return new WP_REST_Response([
        'success' => true,
        'lead_id' => $lead_id,
        'message' => 'Lead submitted successfully',
    ], 201);
}
